from __future__ import annotations

from typing import Protocol

from henry_cloud.domain.models import Approval, ExecutionEvent, Mission


class MissionRepository(Protocol):
    async def create_mission(self, mission: Mission) -> Mission: ...

    async def get_mission(self, mission_id: str) -> Mission | None: ...

    async def save_mission(self, mission: Mission, expected_version: int) -> Mission: ...

    async def list_missions(
        self, owner_id: str | None = None, limit: int = 50
    ) -> list[Mission]: ...

    async def append_event(self, event: ExecutionEvent) -> None: ...

    async def list_events(self, mission_id: str, limit: int = 100) -> list[ExecutionEvent]: ...

    async def create_approval(self, approval: Approval) -> Approval: ...

    async def get_approval(self, approval_id: str) -> Approval | None: ...

    async def save_approval(self, approval: Approval) -> Approval: ...

    async def list_approvals(
        self, status: str | None = None, limit: int = 50
    ) -> list[Approval]: ...
